---
settings:
  cid: !binary |-
    NTVkNWM2YTVhYjYwOGExZTBlMDAwMDNi
  plan_type: BUSINESS
  sub_id: sub_6pX8gcRAWSgnBT
  db: !binary |-
    NTVkNWM2YTVhYjYwOGExZTBlMDAwMDNi
  bucket: 55d5c6a5ab608a1e0e00003bsdfsdsd
