---
settings:
  cid: !binary |-
    NTVkNWM2NDFhYjYwOGExZTBlMDAwMDM4
  plan_type: BUSINESS
  sub_id: sub_6pX7Oq5aq0hHaI
  db: !binary |-
    NTVkNWM2NDFhYjYwOGExZTBlMDAwMDM4
  bucket: 55d5c641ab608a1e0e000038sdfs
