---
settings:
  cid: !binary |-
    NTVkNWM3MzRhYjYwOGExZTBlMDAwMDNl
  plan_type: BUSINESS
  sub_id: sub_6pXB25eMXVTOjQ
  db: !binary |-
    NTVkNWM3MzRhYjYwOGExZTBlMDAwMDNl
  bucket: 55d5c734ab608a1e0e00003e
